root: true
env:
  es6: true
  node: true
  browser: true

parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  project:
    - packages/*/tsconfig.json
    - packages/*/tools/tsconfig.json

plugins:
  - '@typescript-eslint'
  - import

settings:
  import/extensions: [.ts]
  import/parsers:
    '@typescript-eslint/parser': [.ts]
  import/resolver:
    typescript:
      project:
        - packages/*/tsconfig.json
        - packages/*/tools/tsconfig.json
  import/internal-regex: ^@fbe/

extends:
  - eslint:recommended
  - .eslint.base.yml
  # Turn off eslint rules that conflict with typescript-eslint
  - plugin:@typescript-eslint/recommended
  - .eslint.typescript.yml
  # Turn off eslint rules that conflict with prettier
  - prettier
  # Turn off typescript-eslint rules that conflict with prettier
  - prettier/@typescript-eslint
  - .eslint.import.yml
